@startuml
title Диаграмма контекста. Передача актуальных ставок в кол-центры. Банк «Стандарт»

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_TOP_DOWN()

Person(client, "Клиент", "Звонит, чтобы уточнить условия депозита")
Person(ccOperator, "Оператор кол-центра банка", "Консультирует по ставкам")
Person(partnerOperator, "Оператор партнёрского кол-центра", "Консультирует по ставкам в пиковую нагрузку")
Person(boCredit, "Сотрудник бэк-офиса кредитов", "Задаёт параметры расчёта ставок")
Person(boDeposit, "Сотрудник бэк-офиса депозитов", "Согласует ставки")

System(depositPlatform, "Депозитная платформа", "Единый источник ставок банка. Отдаёт ставки по API и публикует файл выгрузки для внешних потребителей")

System(callCenter, "Система кол-центра", "Рабочее место оператора кол-центра банка")
System(sftp, "SFTP-каталог банка", "Изолированная зона обмена файлами с внешними контрагентами")

System_Ext(partnerCallCenter, "Система партнёрского кол-центра", "Внешняя система партнёра. API-вызовы невозможны, обмен только файлами")

Rel(boCredit, depositPlatform, "Вводит параметры расчёта ставок", "Веб-интерфейс")
Rel(boDeposit, depositPlatform, "Согласует ставки", "Веб-интерфейс")

Rel(client, ccOperator, "Звонит и спрашивает условия депозита", "Телефон")
Rel(client, partnerOperator, "Звонит и спрашивает условия депозита", "Телефон")

Rel(depositPlatform, callCenter, "Отдаёт актуальные ставки по запросу", "REST/HTTPS, онлайн")
Rel(ccOperator, callCenter, "Смотрит актуальные ставки в карточке обращения", "Веб-интерфейс")

Rel(depositPlatform, sftp, "Выкладывает файл ставок при каждом изменении и по расписанию", "Файл + манифест")
Rel(partnerCallCenter, sftp, "Забирает файл ставок", "SFTP, по ключу, только чтение")
Rel(partnerOperator, partnerCallCenter, "Смотрит ставки из последнего загруженного файла", "Веб-интерфейс")

@enduml
